env: TOOLCHAIN_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-12-15-a

matrix:
    include:
        - os: osx
          osx_image: xcode8.2
          language: objective-c
          env: TOOLCHAINS=swift
          before_install:
            - curl -O https://swift.org/builds/development/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
            - sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /

        - os: linux
          dist: trusty
          language: generic
          sudo: required
          before_install:
            - sudo apt-get install clang libicu-dev
            - wget https://swift.org/builds/development/ubuntu1404/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-ubuntu14.04.tar.gz
            - wget https://swift.org/builds/development/ubuntu1404/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-ubuntu14.04.tar.gz.sig
            - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
            - gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
            - gpg --verify ${TOOLCHAIN_VERSION}-ubuntu14.04.tar.gz.sig
            - tar xzf ${TOOLCHAIN_VERSION}-ubuntu14.04.tar.gz
            - export PATH=${PWD}/${TOOLCHAIN_VERSION}-ubuntu14.04/usr/bin:"${PATH}"

script: swift build && swift test
