language: objective-c

matrix:
    include:
        - os: osx
          osx_image: xcode8.2
          env: TOOLCHAINS=swift
        - os: linux
          sudo: required
          dist: trusty

script: swift build && swift test

before_install: ./.travis/before_install.sh
