language: objective-c
osx_image: xcode8.2
xcode_project: Swisp.xcodeproj
xcode_scheme: Swisp
env: TOOLCHAINS=swift
script:
- swift build
- swift test
before_install:
- TOOLCHAIN_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-12-15-a
- curl -O https://swift.org/builds/development/xcode/${TOOLCHAIN_VERSION}/${TOOLCHAIN_VERSION}-osx.pkg
- sudo installer -pkg ${TOOLCHAIN_VERSION}-osx.pkg -target /
